"""
MeetingPrepSkill — generate a meeting preparation pack for CDCN board meetings.

The pack includes:
  1. Draft agenda (based on standard template + outstanding items)
  2. Outstanding action points (from action_points table)
  3. Upcoming deadlines (next 30 days from deadlines table)
  4. Policy reviews due
  5. Recent decisions summary (from last 2-3 sets of minutes via retriever)
"""
from __future__ import annotations

import logging
from datetime import date, datetime
from pathlib import Path

from app.config import settings
from app.skills.base import BaseSkill, SkillResult

log = logging.getLogger(__name__)


async def _get_outstanding_actions() -> list[dict]:
    from app.skills.action_tracker import list_actions
    return await list_actions(status="open")


async def _get_upcoming_deadlines(days: int = 30) -> list[dict]:
    from app.skills.deadline_tracker import list_deadlines
    return await list_deadlines(days_ahead=days)


async def _get_policy_reviews_due() -> list[dict]:
    from app.skills.deadline_tracker import list_deadlines
    return await list_deadlines(category="policy_review")


async def _get_recent_minutes_summary(meeting_date: str) -> str:
    """Retrieve summaries from the last 2-3 sets of minutes via vector search."""
    try:
        from app.storage.vector_store import vector_store
        hits = await vector_store.search(
            query="decisions agreed actions outstanding",
            n_results=6,
            doc_type="minutes",
        )
        if not hits:
            return "No recent minutes found in the document archive."
        lines: list[str] = []
        seen_sources: set[str] = set()
        for hit in hits:
            src = Path(hit["source_file"]).name if hit.get("source_file") else ""
            if src in seen_sources:
                continue
            seen_sources.add(src)
            excerpt = hit.get("text", "")[:300].replace("\n", " ")
            lines.append(f"**{src}** (page {hit.get('page_number', 1)}):\n{excerpt}…")
            if len(seen_sources) >= 3:
                break
        return "\n\n".join(lines) if lines else "No recent minutes found."
    except Exception as exc:
        log.warning("Could not retrieve recent minutes: %s", exc)
        return "Recent minutes unavailable."


def _build_pack_markdown(
    meeting_date: str,
    actions: list[dict],
    deadlines: list[dict],
    policy_reviews: list[dict],
    recent_summary: str,
) -> str:
    today = date.today().isoformat()
    lines: list[str] = [
        f"# CDCN Board Meeting — Preparation Pack",
        f"",
        f"**Meeting Date:** {meeting_date}",
        f"**Prepared:** {today}",
        f"",
        f"---",
        f"",
        f"## 1. Draft Agenda",
        f"",
        f"1. Apologies for Absence",
        f"2. Minutes of Previous Meeting — approval",
        f"3. Matters Arising from Minutes",
        f"4. Outstanding Action Points (see Section 2)",
        f"5. Financial Report",
        f"6. Funding Update",
        f"7. Development Officer Report",
        f"8. Upcoming Deadlines (see Section 3)",
        f"9. Any Other Business",
        f"10. Date of Next Meeting",
        f"",
        f"---",
        f"",
        f"## 2. Outstanding Action Points",
        f"",
    ]

    if actions:
        lines.append(f"*{len(actions)} open action(s) as at {today}:*\n")
        for a in actions[:20]:
            due = f" (due {a['due_date']})" if a.get("due_date") else ""
            who = f" — **{a['assigned_to']}**" if a.get("assigned_to") else ""
            lines.append(f"- **{a['action_id']}**{who}: {a['description']}{due}")
    else:
        lines.append("*No outstanding action points.*")

    lines += [
        f"",
        f"---",
        f"",
        f"## 3. Upcoming Deadlines (next 30 days)",
        f"",
    ]

    if deadlines:
        for d in deadlines:
            cat = d["category"].replace("_", " ").title()
            lines.append(f"- **{d['due_date']}** — {d['title']} [{cat}]")
    else:
        lines.append("*No deadlines in the next 30 days.*")

    lines += [
        f"",
        f"---",
        f"",
        f"## 4. Policy Reviews Due",
        f"",
    ]

    if policy_reviews:
        for p in policy_reviews:
            lines.append(f"- **{p['title']}** — due {p['due_date']}")
    else:
        lines.append("*No policy reviews currently due.*")

    lines += [
        f"",
        f"---",
        f"",
        f"## 5. Recent Decisions Summary",
        f"",
        recent_summary,
        f"",
        f"---",
        f"",
        f"*This pack was auto-generated by CDCN Agent. Please verify all information before the meeting.*",
    ]

    return "\n".join(lines)


async def generate_prep_pack(meeting_date: str) -> tuple[str, str]:
    """
    Generate a meeting preparation pack.
    Returns (markdown_text, filename).
    """
    actions = await _get_outstanding_actions()
    deadlines = await _get_upcoming_deadlines(30)
    policy_reviews = await _get_policy_reviews_due()
    recent_summary = await _get_recent_minutes_summary(meeting_date)

    markdown = _build_pack_markdown(
        meeting_date=meeting_date,
        actions=actions,
        deadlines=deadlines,
        policy_reviews=policy_reviews,
        recent_summary=recent_summary,
    )

    safe_date = meeting_date.replace("-", "")
    filename = f"meeting_prep_{safe_date}.md"
    return markdown, filename


async def generate_prep_docx(meeting_date: str) -> tuple[bytes, str]:
    """
    Generate a DOCX version of the prep pack.
    Returns (docx_bytes, filename).
    """
    from app.skills.docx_converter import markdown_to_docx

    markdown, _ = await generate_prep_pack(meeting_date)
    safe_date = meeting_date.replace("-", "")
    filename = f"meeting_prep_{safe_date}.docx"

    docx_bytes = markdown_to_docx(markdown, title=f"Meeting Prep — {meeting_date}")
    return docx_bytes, filename


# ── Skill ─────────────────────────────────────────────────────────────────────


class MeetingPrepSkill(BaseSkill):
    name = "meeting_prep"
    description = (
        "Generate a meeting preparation pack for a CDCN board meeting. "
        "Includes draft agenda, outstanding actions, upcoming deadlines, and recent decisions. "
        "Use when asked to prepare for a meeting or create a meeting pack."
    )

    async def run(self, action_or_dict=None, **kwargs) -> SkillResult:
        if isinstance(action_or_dict, dict):
            kwargs.update(action_or_dict)
        meeting_date = kwargs.get("meeting_date", "") or kwargs.get("date", "")
        if not meeting_date:
            # Default to next occurrence
            from datetime import timedelta
            meeting_date = (date.today() + timedelta(days=7)).isoformat()

        try:
            markdown, filename = await generate_prep_pack(meeting_date)
            return SkillResult(
                success=True,
                output=markdown,
                metadata={"filename": filename, "meeting_date": meeting_date},
            )
        except Exception as exc:
            log.exception("MeetingPrepSkill.run failed")
            return SkillResult(success=False, error=str(exc))
